trigger:
- master

jobs:
- job: changed_customers
  displayName: FindChangedCustomers
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 30
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        $files=$(git diff HEAD HEAD~ --name-only)
        echo $files

        $temp=$files -split ' '
        $count=$temp.Length
        echo "Total changed $count files"

        For ($i=0; $i -lt $temp.Length; $i++)
        {
          $name=$temp[$i]
          echo "this is $name file"
          if ($name -like "development/*")
            {
              Write-Host "##vso[task.setvariable variable=development]True"
            }
          if ($name -like "customern/*")
            {
              Write-Host "##vso[task.setvariable variable=customern]True"
            }
        }
    name: changed

- job: development
  displayName: DevelopmentCustomer
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 30
  dependsOn: changed_customers
  condition: eq(dependencies.changed_customers.outputs['changed.development'], 'true')
  steps:
  - script: echo Development changed

- job: customern
  displayName: CustomernCustomer
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 30
  dependsOn: changed_customers
  condition: eq(dependencies.changed_customers.outputs['changed.customern'], 'true')
  steps:
  - script: echo Customern changed
