trigger:
- master

jobs:
- job: changed_customers
  displayName: FindChangedCustomers
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 30
  steps:
  - checkout: self
  - bash: |
        changes=$(git diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]\+% //g')
        echo $changes

        for customer in $changes
        do
          echo Checking $customer
          if [[$customer == "development/"]]
            echo "##vso[task.setvariable variable=development]True"
          fi
          if [[$customer == "customern/"]]
            echo "##vso[task.setvariable variable=customern]True"
          fi
        done
    name: changed

- job: development
  displayName: DevelopmentCustomer
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 30
  dependsOn: changed_customers
  condition: eq(dependencies.changed_customers.outputs['changed.development'], 'true')
  steps:
  - bash: echo Development changed

- job: customern
  displayName: CustomernCustomer
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 30
  dependsOn: changed_customers
  condition: eq(dependencies.changed_customers.outputs['changed.customern'], 'true')
  steps:
  - bash: echo Customern changed
