trigger:
- master

variables:
- name: variable1
  value: "firstvariable"

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: FirstStage
  jobs:
  - job: FirstStageFirstJob
    displayName: FirstStageFirstJob
    timeoutInMinutes: 5
    steps:
    - bash: echo $(variable1)
    - bash: |
        echo Create boolean
        echo "##vso[task.setvariable variable=outputvariable;isOutput=true]True"
      name: outputstep
    - bash: |
        echo New variable
        echo "##vso[task.setvariable variable=variable2;isOutput=true]secondvariable"
      name: firststagevariable

  - job: FirstStageSecondJob
    displayName: FirstStageSecondJob
    dependsOn: FirstStageFirstJob
    condition: eq(dependencies.FirstStageFirstJob.outputs['outputstep.outputvariable'], 'true')
    timeoutInMinutes: 10
    steps:
    - bash: echo $[ dependencies.FirstStageFirstJob.outputs['firststagevariable.variable2'] ]

- stage: SecondStage
  jobs:
  - job: SecondStageFirstJob
    displayName: SecondStageFirstJob
    timeoutIntMinutes: 5
    steps:
    - bash: echo Second stage

- stage: FinalStage
  jobs:
  - job: FinalStageFirstJob
    displayName: FinalStageFirstJob
    timeoutIntMinutes: 5
    steps:
    - bash: echo Cleaning pipeline
