# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - $(customer)/*

variables:
- group: customer-pipelines-variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(customer)
  displayName: 'Run a one-line script'

- script: |
    echo Deploy to $(cluster-name)
    echo Static $(static)
  displayName: 'Run a multi-line script'
